<?php

namespace PaymentBundle\Repository;

/**
 * PaymentActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
