<?php

namespace PaymentBundle\Repository;

/**
 * PaymentInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
