<?php

namespace PaymentBundle\Repository;

/**
 * TransactionActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
