# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        UserBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_db:
            entity:
                class: UserBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # note that anonymous access is now enabled

        main:
            anonymous: true
            # activate different ways to authenticate
            pattern:    ^/
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: /login
                check_path: /login
                success_handler: security.login_handler.success.service
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: [ ROLE_DESKIMO_ADMIN, ROLE_DESKIMO_STAFF, ROLE_PROPERTY_ADMIN, ROLE_PROPERTY_CLERK, ROLE_CORPORATE_ADMIN, ROLE_CORPORATE_USER ] }
