controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app:
    resource: "@AppBundle/config/routes.yaml"
    prefix:   /app

html:
    resource: "@HtmlBundle/config/routes.yaml"
    prefix:   /html

home:
    resource: "@HomeBundle/config/routes.yaml"
    prefix: /

admin:
    resource: "@AdminBundle/config/routes.yaml"
    prefix:   /admin

agent:
    resource: "@AgentBundle/config/routes.yaml"
    prefix:   /agent

user:
    resource: "@UserBundle/config/routes.yaml"
    prefix:   /



