controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

html:
    resource: "@HtmlBundle/config/routes.yaml"
    prefix:   /html

home:
    resource: "@HomeBundle/config/routes.yaml"
    prefix: /

admin:
    resource: "@AdminBundle/config/routes.yaml"
    prefix:   /admin

user:
    resource: "@UserBundle/config/routes.yaml"
    prefix:   /

#api_login_check:
#    path: /api/login_check

