<?php

namespace UserBundle\Utils;

class RolesUtil
{
  const ROLE_CORPORATE_USER = 'ROLE_CORPORATE_USER';
  const ROLE_CORPORATE_ADMIN = 'ROLE_CORPORATE_ADMIN';
  const ROLE_PROPERTY_CLERK = 'ROLE_PROPERTY_CLERK';
  const ROLE_PROPERTY_ADMIN = 'ROLE_PROPERTY_ADMIN';
  const ROLE_DESKIMO_STAFF = 'ROLE_DESKIMO_STAFF';
  const ROLE_DESKIMO_ADMIN = 'ROLE_DESKIMO_ADMIN';

  const ROLE_CORPORATE_USER_ID = 1;
  const ROLE_CORPORATE_ADMIN_ID = 2;
  const ROLE_PROPERTY_CLERK_ID = 4;
  const ROLE_PROPERTY_ADMIN_ID = 5;
  const ROLE_DESKIMO_STAFF_ID = 6;
  const ROLE_DESKIMO_ADMIN_ID = 7;

  const ADMIN_DEFAULT_ROUTE = 'admin_dashboard_route';

  //role title
  const ROLE_CORPORATE_USER_TITLE = 'Corporate user';
  const ROLE_CORPORATE_ADMIN_TITLE = 'Corporate admin';
  const ROLE_PROPERTY_CLERK_TITLE = 'Property staff';
  const ROLE_PROPERTY_ADMIN_TITLE = 'Property admin';
  const ROLE_DESKIMO_STAFF_TITLE = 'Deskimo staff';
  const ROLE_DESKIMO_ADMIN_TITLE = 'Deskimo admin';

  const ROLE_MAPPING = [
    self::ROLE_CORPORATE_USER_ID => self::ROLE_CORPORATE_USER,
    self::ROLE_CORPORATE_ADMIN_ID => self::ROLE_CORPORATE_ADMIN,
    self::ROLE_PROPERTY_CLERK_ID => self::ROLE_PROPERTY_CLERK,
    self::ROLE_PROPERTY_ADMIN_ID => self::ROLE_PROPERTY_ADMIN,
    self::ROLE_DESKIMO_STAFF_ID => self::ROLE_DESKIMO_STAFF,
    self::ROLE_DESKIMO_ADMIN_ID => self::ROLE_DESKIMO_ADMIN
  ];

  const CAN_ASSIGN_PERMISSION_ROLE_MAPPING = [
    self::ROLE_CORPORATE_USER_ID => self::ROLE_CORPORATE_USER_TITLE,
    self::ROLE_CORPORATE_ADMIN_ID => self::ROLE_CORPORATE_ADMIN_TITLE,
    self::ROLE_PROPERTY_CLERK_ID => self::ROLE_PROPERTY_CLERK_TITLE,
    self::ROLE_PROPERTY_ADMIN_ID => self::ROLE_PROPERTY_ADMIN_TITLE,
    self::ROLE_DESKIMO_STAFF_ID => self::ROLE_DESKIMO_STAFF_TITLE,
    self::ROLE_DESKIMO_ADMIN_ID => self::ROLE_DESKIMO_ADMIN_TITLE
  ];

  const ROLE_DEFAULT_ROUTE = [
    self::ROLE_CORPORATE_USER => self::ADMIN_DEFAULT_ROUTE,
    self::ROLE_CORPORATE_ADMIN => self::ADMIN_DEFAULT_ROUTE,
    self::ROLE_PROPERTY_CLERK => self::ADMIN_DEFAULT_ROUTE,
    self::ROLE_PROPERTY_ADMIN => self::ADMIN_DEFAULT_ROUTE,
    self::ROLE_DESKIMO_STAFF => self::ADMIN_DEFAULT_ROUTE,
    self::ROLE_DESKIMO_ADMIN => self::ADMIN_DEFAULT_ROUTE
  ];

  const CAN_ASSIGN_WHEN_INVATING_COMPANY = [
    self::ROLE_PROPERTY_CLERK_ID => self::ROLE_PROPERTY_CLERK_TITLE,
    self::ROLE_PROPERTY_ADMIN_ID => self::ROLE_PROPERTY_ADMIN_TITLE,
  ];

  public static function getTargetPathByRole($roleName)
  {
    return isset(self::ROLE_DEFAULT_ROUTE[$roleName]) ? self::ROLE_DEFAULT_ROUTE[$roleName] : self::ADMIN_DEFAULT_ROUTE;
  }
}
