# config/routes.yaml
#api_user_login_route:
#  path:       /api/login
#  controller: App\Bundle\UserBundle\Controller\Api\ApiUserController::login

user_login:
  path:       /user/login
  controller: App\Bundle\UserBundle\Controller\User\UserController::login
  methods: ['GET','POST']

user_logout:
  path:       /user/logout
  controller: App\Bundle\UserBundle\Controller\User\UserController::logout

user_register:
  path: /user/register
  controller: App\Bundle\UserBundle\Controller\User\UserController::register
  methods: ['GET','POST']

user_forgot_password:
  path: /user/forgot-password
  controller: App\Bundle\UserBundle\Controller\User\UserController::forgotPassword
  methods: [ 'GET','POST' ]

user_reset_password:
  path: /user/reset-password/{token}
  controller: App\Bundle\UserBundle\Controller\User\UserController::resetPassword
  methods: [ 'GET','POST' ]

api_login:
    path: /api/login
    controller: App\Bundle\UserBundle\Controller\Api\UserController::login
    methods: ['POST']

admin_login:
  path:       /admin/login
  controller: App\Bundle\UserBundle\Controller\Admin\UserController::login

api_register:
  path: /api/register
  controller: App\Bundle\UserBundle\Controller\Api\UserController::register
  methods: POST