parameters:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      App/Bundle/UserBundle/Controller/UserController: ~

    App\Bundle\UserBundle\Services\UserService:
      shared: true


