<?php

namespace UserBundle\Repository;

/**
 * CustomerPaymentGatewayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPaymentGatewayRepository extends \Doctrine\ORM\EntityRepository
{
}
